### ISSUE TITLE
pypi new version publish

### ISSUE THREAD

**Issue by secularbird** [P4N74/demangler#4]
Do you have any plan to publish the new package to pypi?

**Comment by r-jenish** [comment]
I don't think there is any change in the code after previous release

**Comment by secularbird** [comment]
I have check the pypi web sit, there is a demangler, which is version 0.2, but when i using pip to install it, it's version is always 0.1, detail log as below.

```bash
$ pip install --upgrade demangler
Collecting demangler
  Using cached https://files.pythonhosted.org/packages/01/dc/9c71637c7cfadf35ae2080649932c3b2a6de68cbc7172bcd187800540656/Demangler-0.1.tar.gz
Building wheels for collected packages: demangler
```

**Comment by secularbird** [comment]
And I can search it， but I can't install it, I don't know why

`pip search demangler`
<pre>
Demangler (0.2)  - A demangler package for gcc 3.x and gcc 4.x
</pre>

`pip install demangler==0.2`
<pre>
pip install demangler==0.2
Collecting demangler==0.2
  Could not find a version that satisfies the requirement demangler==0.2 (from versions: 0.1)
No matching distribution found for demangler==0.2
</pre>

**Comment by r-jenish** [comment]
I think that you should be able to install version 0.2 now. Can you please check and verify it so that I can close the issue.

Sorry for the delay. :)

**Comment by secularbird** [comment]
I have checked, it's ok now. Thank you. :)
